service:
  name: roles-auths-virre-client
spring:
  application:
    name: roles-auths-virre-client
eureka:
  instance:
      statusPageUrlPath: /info
      healthCheckUrlPath: /health
      preferIpAddress: true
      non-secure-port: 0
  client:
    enabled: false

